# Generated by Django 4.1.2 on 2022-10-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_page_interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(upload_to='images'),
        ),
    ]
