# Generated by Django 4.1.2 on 2022-10-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_page_interface', '0002_alter_customuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(upload_to='face_page/media/images'),
        ),
    ]
