# Generated by Django 4.1.2 on 2022-10-20 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_page_interface', '0011_alter_post_users_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='users_liked',
        ),
    ]
