# Generated by Django 4.1.2 on 2022-10-20 23:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('face_page_interface', '0012_remove_post_users_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='users_liked',
            field=models.ManyToManyField(related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
