# Generated by Django 4.1.2 on 2022-10-22 15:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('face_page_interface', '0013_post_users_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='friends',
            field=models.ManyToManyField(related_name='friend', to=settings.AUTH_USER_MODEL),
        ),
    ]
