# Generated by Django 4.1.2 on 2022-10-25 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('face_page_interface', '0015_remove_customuser_friends_customuser_followers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='customuser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='face_page_interface.customuser'),
        ),
    ]
